// src/app/features/recipes/models/recipe.model.ts

export interface Ingredient {
  name: string;
  qty?: number;
  unit?: string;
  prep?: string;
}

export interface Step {
  order: number;
  text: string;
  time?: number;            // minutes
  concurrent_group?: number;
}

export type Difficulty = 'easy' | 'medium' | 'hard';

export interface Recipe {
  id: string;
  user_id: string;
  name: string;
  description?: string;
  cuisine_type?: string;
  language: string;
  prep_time?: number;
  cook_time?: number;
  total_time?: number;      // generated by DB
  servings?: number;
  difficulty?: Difficulty;
  equipment: string[];
  ingredients: Ingredient[];
  steps: Step[];
  tags: string[];
  allergens: string[];
  image_path?: string;
  source_file?: string;
  created_at: string;
  is_favorite?: boolean;    // joined from favorite_recipes, not a DB column
}

export interface RecipeFilter {
  query?: string;
  ingredients?: string[];
  cuisine_type?: string;
  max_time?: number;
  equipment_required?: string[];
  allergens_exclude?: string[];
  difficulty?: Difficulty;
  favorites_only?: boolean;
}

export interface ImportJob {
  id: string;
  user_id: string;
  file_path: string;
  status: 'pending' | 'processing' | 'done' | 'error';
  error_msg?: string;
  created_at: string;
}
